In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.mixture import GaussianMixture
from sklearn.datasets import make_blobs
import seaborn as sns

In [3]:
data, true_labels = make_blobs(n_samples=300, centers=3, cluster_std=2.0, random_state=42)

In [4]:
data

array([[ -7.79834899,  -8.57979833],
       [ -8.60045392,  -7.64922068],
       [ -0.8641078 ,   6.57259883],
       [  4.20451643,   4.17072339],
       [-10.95587626,  -8.89628222],
       [  6.35519808,   1.65329262],
       [ -2.16283577,   9.78492089],
       [  5.46574174,   0.84572058],
       [ -3.4675461 ,   8.64296817],
       [ -4.89180462,  10.32739335],
       [ -3.71261085,  12.7188425 ],
       [  5.35390981,   0.58735049],
       [ -2.09147043,   5.09494588],
       [ -5.33993911,   8.17299548],
       [ -8.18091233,  -7.85436036],
       [ -3.91330381,   8.35896184],
       [-10.13471207,  -6.7839397 ],
       [  0.58959366,   2.34607831],
       [ -2.31504252,  10.95157611],
       [ -1.33548344,  13.39519738],
       [ -0.19200647,   7.37292149],
       [ -2.83176905,   9.82238784],
       [  6.5901183 ,   1.67905492],
       [ -7.10428329,  -7.32204879],
       [ -3.43603301,   8.08282662],
       [ -5.82001884,  -3.99697235],
       [ -8.03316985,  -5.36932714],
 

In [5]:
plt.scatter(data[:, 0], data[:, 1], s=30)
plt.title("Generated Data")
plt.show()

In [6]:
gmm = GaussianMixture(n_components=3, random_state=42)
gmm.fit(data)

GaussianMixture(n_components=3, random_state=42)

In [8]:
print("Means:\n", gmm.means_)

Means:
 [[-2.75050072  9.0732438 ]
 [-6.88271329 -7.08025394]
 [ 4.85448595  2.05010271]]


In [9]:
predicted_labels = gmm.predict(data)

In [10]:
plt.scatter(data[:, 0], data[:, 1], c=predicted_labels, s=30, cmap='viridis')
plt.title("GMM Clustering Results")
plt.show()

In [12]:
new_data = np.array([[0, 0], [10, 10], [-10, -10]])
predictions = gmm.predict(new_data)
pred_probabilities = gmm.predict_proba(new_data)
print("Predictions for new data points:\n", predictions)
print("Prediction probabilities for new data points:\n", pred_probabilities)

Predictions for new data points:
 [2 2 1]
Prediction probabilities for new data points:
 [[2.21179187e-04 8.54228077e-04 9.98924593e-01]
 [2.45971798e-06 1.09705930e-22 9.99997540e-01]
 [1.35750302e-22 1.00000000e+00 4.58914386e-23]]
