In [15]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [3]:
digits = load_digits()
X = digits.data
y = digits.target
print(X)
print(y)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]


In [12]:
X.shape

(1797, 64)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 5, 10, 20],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_samples': [0.5, 0.7, 1.0],
    'max_leaf_nodes': [None, 7, 10, 20, 30]
}

In [9]:
rf_grid = GridSearchCV(estimator=RandomForestClassifier(random_state=42),param_grid=param_grid,cv=5,n_jobs=-1,verbose=2,scoring='accuracy')
rf_grid.fit(X_train, y_train)

Fitting 5 folds for each of 540 candidates, totalling 2700 fits


c:\jupyter\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
900 fits failed out of a total of 2700.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
245 fits failed with the following error:
Traceback (most recent call last):
  File "c:\jupyter\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\jupyter\.venv\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\jupyter\.venv\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constrain

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [None, 5, 10, 20],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'max_leaf_nodes': [None, 7, 10, 20, 30],
                         'max_samples': [0.5, 0.7, 1.0],
                         'n_estimators': [50, 100, 150]},
             scoring='accuracy', verbose=2)

In [21]:
rf_grid.best_score_

np.float64(0.9749540263259776)

In [13]:
y_pred = rf_grid.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy : {accuracy}')

Accuracy : 0.9722222222222222


In [16]:
feature = pd.DataFrame({'feature':digits.feature_names,'importance':rf_grid.best_estimator_.feature_importances_}).sort_values(by='importance', ascending=False)

In [18]:
feature

feature  importance
21  pixel_2_5    0.044725
43  pixel_5_3    0.042857
26  pixel_3_2    0.041897
36  pixel_4_4    0.039069
42  pixel_5_2    0.036829
..        ...         ...
56  pixel_7_0    0.000056
40  pixel_5_0    0.000048
0   pixel_0_0    0.000000
32  pixel_4_0    0.000000
39  pixel_4_7    0.000000

[64 rows x 2 columns]