In [110]:
import numpy as np

integers

In [111]:
np.random.randint(10)

9

In [112]:
np.random.randint(10,size=2)

array([2, 3], dtype=int32)

In [126]:
x = np.random.randint(-100,100,size=20)
x

array([-95,  21,  91,  21,  -4, -51,  61, -28,  41, -88, -37,   3, -97,
        59,  19,  17,  75,  53,  55,  -8], dtype=int32)

float

In [114]:
#0 to 1
np.random.rand(10)

array([0.06286854, 0.74938671, 0.45328172, 0.65542077, 0.70063586,
       0.18461175, 0.61854522, 0.45099077, 0.51158218, 0.59275197])

In [115]:
np.random.random(10)

array([0.78567183, 0.12497904, 0.40998958, 0.57508709, 0.2906392 ,
       0.30061861, 0.85066797, 0.7067589 , 0.4246327 , 0.77662763])

In [116]:
np.random.rand(5,6,5)#size

array([[[0.77021276, 0.73939351, 0.80199254, 0.07480627, 0.04880528],
        [0.70495772, 0.61139422, 0.23149673, 0.91688507, 0.37609936],
        [0.60263863, 0.15820855, 0.2866209 , 0.41534921, 0.54617993],
        [0.19845442, 0.82321178, 0.91282003, 0.71317724, 0.56103202],
        [0.60638961, 0.58688282, 0.54228322, 0.05761304, 0.74749486],
        [0.05279795, 0.6464764 , 0.36504382, 0.47096553, 0.0524593 ]],

       [[0.90523849, 0.96701984, 0.20281897, 0.88106428, 0.81256809],
        [0.14022844, 0.97043474, 0.26720658, 0.47001263, 0.07180459],
        [0.12589998, 0.27844573, 0.76029597, 0.40768246, 0.36235794],
        [0.23593632, 0.66260396, 0.65046572, 0.41191284, 0.27242236],
        [0.01378276, 0.30509355, 0.51941236, 0.92401575, 0.89943455],
        [0.11199057, 0.99781005, 0.85465328, 0.13478093, 0.09288772]],

       [[0.55071222, 0.05540418, 0.43596728, 0.05224719, 0.42183329],
        [0.31146404, 0.89000191, 0.30143801, 0.69461205, 0.15079464],
        [0.51495

In [117]:
np.random.uniform(-10,10,size=(2,2))

array([[ 8.3489496 ,  2.62855847],
       [-1.62083418,  9.86558314]])

normal distribution

In [118]:
np.random.randn(1,2)

array([[-0.83277044,  0.5139807 ]])

In [119]:
np.random.normal(loc=5,scale= 3,size= 10)

array([5.14657269, 1.75101216, 8.94927426, 2.74462481, 2.65003681,
       3.11225273, 4.18121043, 5.58318941, 9.58525632, 7.27876798])

from list choosing one

In [120]:
np.random.choice(['apple', 'banana', 'cherry'], size=2)


array(['apple', 'banana'], dtype='<U6')

In [121]:
np.random.choice(['apple', 'banana', 'cherry'], size=2,replace=True)

array(['apple', 'apple'], dtype='<U6')

In [122]:
np.random.choice(['apple', 'banana', 'cherry'], size=2,replace=True,p=[0.2,0.2,0.6])


array(['cherry', 'cherry'], dtype='<U6')

shuffling

In [136]:
np.random.permutation(x)

array([ 17, -51,  91,  -8, -95,  61, -97,  -4,  59,  21,  41, -37,  55,
        19, -88,  53, -28,   3,  75,  21], dtype=int32)

In [ ]:
np.random.shuffle(x)#inplace = true
x

array([-95,  61,  21,  75, -51,  59,  19, -37,  -4,  17, -97,  41,  21,
        55,  -8, -88,  53, -28,  91,   3], dtype=int32)